package Enumerados;

public enum EstadoSprite {
    BASE_IZQUIERDA,
    BASE,
    BASE_DERECHA,
    SALTO_DERECHA,
    SALTO_IZQUIERDA,
    LANZAR_IZQUIERDA,
    LANZAR_DERECHA,
    EMPUJANDO_IZQUIERDA,
    EMPUJANDO_DERECHA,
    PATEAR_IZQUIERDA,
    PATEAR_DERECHA,
    MUERTE,
    ATURDIDO,
    IZQUIERDA,
    DERECHA,
    APARICION,
    ESCALANDO,
    EXPLOSION,
    CAYENDO_DERECHA,
    CAYENDO_IZQUIERDA,
    FINAL,
    DANIO,
    SUBIDA,
    ATAQUE;
}
